trigger:
  branches:
    include:
      - main  # Altere para o nome da sua branch principal

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restaurar pacotes'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Criar publicação'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar artefatos de build'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Implantar no Azure App Service'
    inputs:
      azureSubscription: '8b6f2f6e-284c-48d1-9cfd-b88d0b536777'
      appType: 'webApp'
      WebAppName: 'api-produto'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'